### ISSUE TITLE
Too much irony and delusion

### ISSUE THREAD

**Issue by ghost** [prettydiff/wisdom#7]
https://github.com/prettydiff/wisdom/blob/master/Delusional_Developers.md

> One of the common supporting opinions is that JavaScript is only popular because it executes on webpages. I have been writing JavaScript long enough to know *this doesn't make any sense*.

That's a delusion.

> Delusions are a serious of weak opinions joined together to create a false sense of the world.

Right! Ignoring flaws because of "Cognitive Conservatism".

> As an example in development a developer may form the opinion that JavaScript is a bad sloppy language.

That's not an opinion. That's a fact. There's plenty of evidence supporting that argument. You may think that it's false - but that's just "Wishful Thinking":

https://github.com/prettydiff/wisdom/blob/master/Bad_Developers.md

> ...The challenge with this path is that although factually accurate it doesn't often align with the reality of entering the marketplace for that first big career. It is often easier to get an *entry level job as a web developer* than as a Java developer due to *lower barrier to entry*.

Expert beginners. Clear?

> Rockstar developers achieve their status through providing better solutions. When developers struggle all their energy on how to write code they loose focus of what to write more importantly why.

**Comment by prettydiff** [comment]
> That's not an opinion. That's a fact.

I think you should research difference between truth and fact.  Evidence does not transform an opinion into a fact.  Arguments are never facts.

**Comment by ghost** [comment]
Dear @prettydiff, first you need to decide how do you want to qualify that assertion: a) as an argument or b) as an opinion or c) as a "truth". Those are different things and they might not be what you think they are.

Second:

> *Evidence*, broadly construed, is anything presented in support of an assertion. The strongest type of evidence is that which provides direct proof of the truth of an assertion.

Proven assertions are facts:

> A *fact* is a thing that is known to be consistent with objective reality and can be proven to be true with evidence.

So:

> As an example in development a developer may form the opinion that JavaScript is a bad sloppy language. *I have been writing JavaScript long enough to know this doesn't make any sense.*

That is just a denial without a counterargument.

> As an example in development a developer may form the opinion that JavaScript is a bad sloppy language.

That's *not* an opinion:

> An *opinion* is a judgment, viewpoint, or statement that is *not conclusive*.

Javascript being a poorly designed language is not an opinion because there are plenty of empirical, theoretical and technical arguments/evidence objectively(and relatively to today's standards) criticizing javascript's typesystem, object system, memory management etc. On the other hand, the counterarguments(if we can call them that...) usually consist of sentences like "in my experience it's ok" or "it's fine, look at the popularity of our tool!" or "look how much people ask questions about it". Just think about what you said: "It is often easier to get an entry level job as a web developer than as a Java developer due to lower barrier to entry.".

No one said that arguments are facts - arguments are assertions which can be *proofs*. Arguments which are consistent with reality can turn assertions into facts. Evidence doesn't transform an opinion into a fact because if there's an evidence supporting that assertion then it's not an opinion but a fact. Denying a consistent evidence doesn't turn a fact in to an opinion - unless the denial has a real and stronger evidence attached to it.

For example, there are plenty of evidence showing that the Earth has a spheroidal shape. The Earth being "round" is not an opinion but a fact because we can prove that. On the other hand, if you say that it's flat then it's still not an opinion but a delusion.

Your "evidence" is just a *subjective* statement supported by nothing. If you want to write about [delusional developers](https://github.com/prettydiff/wisdom/blob/master/Delusional_Developers.md), first you need to get rid of your delusions about javascript and critical thinking. Accepting the illusions of productivity, popularity and technical fitness can not create a solid foundation for technical excellence which is what you meant by "rockstar developers"(which is a joke).

**Comment by prettydiff** [comment]
> Those are different things

They are not.

* truth - agreement via confirmation: https://www.dictionary.com/browse/truth
* opinion - a belief: https://www.dictionary.com/browse/opinion?s=t
* argument - a challenge: https://www.dictionary.com/browse/argument?s=t

All conclusions, logic, are opinions.  Logic may be either fallible or valid, but it is still always an opinion.  Proofs are demonstrable logic.  Truths and arguments are always opinions.  An argument becomes a truth once agreement is met.  Truths also don't require evidence as logic alone is sufficient, even if incomplete or poorly formed.  For a more thorough explanation read chapter 2 of On Liberty: https://www.bartleby.com/130/

To be a fact these three criteria must be met and not exceeded by additional qualities:
* a thing
* existing
* existence is in reality; as opposed to philosophy, abstractions, dreams, or illusions

**Comment by ghost** [comment]
> They are not.

And then you disprove yourself with your links:

> truth - agreement via confirmation

Absolutely not. The truth doesn't need general agreement: *"conformity with fact or reality; verity"* - it only needs to represent the reality. You will also disagree with yourself and with your link later.

> opinion - a belief; argument - a challenge

Very different things. But hold on:

> Argument: a statement, reason, or *fact* for or against a point

You said that: *"Arguments are never facts."* - but your link disagrees with you.

> All conclusions, logic, are opinions.

Opinions are inconclusive assertions: *"a belief or judgment that rests on grounds insufficient to produce complete certainty."*. Arguments and opinions are *statements*. An opinion is something that can't be taken as true because it lacks sufficient proof. An argument is something that you can use to prove another statement.

> Logic may be either fallible or valid, but it is still always an opinion.

Fallible logic is a weak argument. Valid logic is proof.

>  Proofs are demonstrable logic.

No, proofs can be empirical too.

>  Truths and arguments are always opinions.

Only if you change the meaning of opinion.

> An argument becomes a truth once agreement is met. 

1. An agreement is not required for something to be true 2. an argument is either true, false or weak.

>  Truths also don't require evidence as logic alone is sufficient, even if incomplete or poorly formed.

Here is where you disagree with yourself and with your link. An incomplete logical argument is not a proof, therefore your statement is still just an opinion and not real truth.

> To be a fact these three criteria must be met and not exceeded by additional qualities:

Those criteria are very poorly formed:

> a thing; existing

That's controversial to this:

> existence is in reality; as opposed to philosophy, abstractions, dreams, or illusions

which doesn't conform with reality: math is an abstraction. Math knows facts.

When you design a language you need to select features. Your features need to cooperate in a nice way but most importantly you need to select/design your features by the following aspects:

1. performance

2. memory efficiency

3. productivity

4. safety

5. readability

6. flexibility

7. accessibility(like learning)

People say that javascript is a poorly designed language because its features concentrate on *flexibility* in a way that it hurts other aspects like performance, memory eff., safety, readability and accessibility(see operator behavior). And why is that statement right? Because in comparison to contemporary languages those features could have been implemented in a far better way. Javascript was not "designed" - we know that it has been slapped together in 10 days by someone who actually wanted to create something else.

**Comment by prettydiff** [comment]
Conformity is agreement and truth isn't limited to reality.

Arguments are never facts.   The definition you quoted does **not** only say **a statement, reason, or fact**.  It says **a statement, reason, or fact for or against a point**.  As it points out its use of the word fact must be connected to a point of the conversation. A fact linking to an assertion is a conclusion, which is an option, and more than the mere fact itself.  It is important to not slice off part of the definition.

Since you bring up conclusiveness let me point to the triangle.  Euclid firmly established that the angles of a triangle add up to 180 degrees.  This is proven mathematically and it is conclusive.  Many people would call that a fact because it is so firmly established for over 2000 years, even though it does not fit the definition of a fact.  In the late 16th century this was proven wrong, with mathematical proofs.  When you map a triangle to the surface volume of a 3D space the sum of its angles is 270 degrees.  An equilateral triangle mapped to the surface of a sphere contains three right angles.

To say the angles of a triangle must always add up to 180 degrees is not accurate.  If truth were a factor of factual nature then this must not be a fact as it is proven false with a math proof.  Does that make it an opinion?  If opinions must be inconclusive then it must also not be an opinion as the nature of triangles is conclusive.  If arguments are factual when supported by facts the disputed nature of triangles must be a fact even when truth is not confirmed.  None of this makes sense and quickly falls apart in complexity.  

Facts are simple and primitive.

Worse still are syllogisms.  Many people who view argumentation as factual may find syllogisms as a natural expression of fact, but this also is incorrect and full of gaps.  The quality that makes syllogisms opinions is the exact same thing that makes them arguments: deduction (logic).  Syllogisms only work when the inclusion of one thing into another is not contested, but this rule is implicit to the deductive logic and not stated.  That is problematic because it is a weak assumption and also because there is no rule demanding the two qualities of the assertion are static in their relationship.

In the spirit of syllogisms:

All syllogisms are deductive arguments expressed as facts.  All deductions are opinions.    Therefore all factual sounding syllogisms are opinions.

**Comment by ghost** [comment]
> Conformity is agreement and truth isn't limited to reality.

We are talking about facts. Conformity or agreement has nothing to do with truth.

> Arguments are never facts. The definition you quoted does not only say a statement, reason, or fact. It says a statement, reason, or fact for or against a point.

Read that again: *or fact for or against a point* - this means that a fact can be an argument if it's used for or against an assertion. You can use facts as arguments to describe reality's properties: you can say that "I think the Earth is flat" and then I present gravity - it's both a fact and an argument.

> A fact linking to an assertion is a conclusion

It isn't (yet).

> which is an option, and more than the mere fact itself. It is important to not slice off part of the definition.

What's even more important is not to misinterpret it completely.

> To say the angles of a triangle must always add up to 180 degrees is not accurate. If truth were a factor of factual nature then this must not be a fact as it is proven false with a math proof. Does that make it an opinion?

Yes and no: it's a theory. A theory is an opinion which is widely accepted but lacks a strong proof or its existing proofs didn't deal with other properties of relevant reality.

> If opinions must be inconclusive

Yes.

> then it must also not be an opinion as the nature of triangles is conclusive.

An opinion doesn't need to be true.

> If arguments are factual when supported by facts the disputed nature of triangles must be a fact even when truth is not confirmed. None of this makes sense and quickly falls apart in complexity.

There's no problem here. If you want to support an argument with a fact then you need to make sure that the fact itself is relevant and the argument is properly generalized. Otherwise, it's just a theory.

> Facts are simple and primitive.

There's no such criteria. BUT the fact we were originally talking about is very simple.

> Worse still are syllogisms. Many people who view argumentation as factual may find syllogisms as a natural expression of fact, but this also is incorrect and full of gaps.

I didn't say that so I don't know why do you think that it's relevant. I never said that argumentation is factual and I didn't use any syllogism.

> All syllogisms are deductive arguments expressed as facts. All deductions are opinions. Therefore all factual sounding syllogisms are opinions.

So reasoning is not always consistent with reality - this is not a new thing. 

Things have properties. The properties can have effects. The effects' values can range from very negative to very positive in each possible environment. We can analyze these properties and then compare the effects of competing properties in various environments. The data can be used to create new assertions - if it's linked and generalized properly.

**Comment by prettydiff** [comment]
Conformity is a type of agreement.  Agreement is required to attain truth.  Anything in dispute is not true.

Facts alone are not arguments.  Facts can be used as the basis of arguments, or any form of logic, by linking a fact to an assertion.  A common example is a syllogism.  A syllogism is an argument based upon facts, but is not a fact.

Scientifically speaking your understanding of theories is wrong.  Theories can never be proven regardless of any possible evidence and proofs.  Theories can only be disproved.  That means theories can never be a proof.

Facts don't need to be true either.  A fact is false if it is disagreed.  Disagreeing with a fact does not transform a fact into an opinion.  Facts are opinions are different and non-exchangeable.  Facts can be proven true with supporting evidence or false when challenged by evidence.  Truth is always an opinion and facts are not opinions.  An example is a memory.  A memory is a thing that exists and that existence is in reality, such that a person really does have a memory.  A person can document the contents of a memory, but memories are often proven false.  The memory does not cease to exist because it is false.  Existence of the memory is not eliminated by proving the memory false.  When the memory is proven false the memory continues to exist, but it's contents are disagreed.

In language people often confuse the agreed state of a thing as a fact, but agreement exceeds factual nature.  The word *fact* comes from the Latin equivalent of the English *do*, *facere*.  The doable nature, possible, of a thing does not equivocate to an agreeable nature, probable.

**Comment by ghost** [comment]
> Agreement is required to attain truth.

No it isn't. Truth doesn't care about opinions.
Just because you don't agree with something it can still be true.

> Anything in dispute is not true.

Then I guess "the Earth is spheroidal" statement is not true... and nothing can be true because anyone can dispute them.

> Facts alone are not arguments.

Facts can be used as arguments - this is what I and the definition said. Facts are facts. When you use them as arguments they become arguments too.

> Facts can be used as the basis of arguments, or any form of logic, by linking a fact to an assertion.

Facts are in the category of assertions. Assertions supporting assertions are arguments.

> A common example is a syllogism. A syllogism is an argument based upon facts, but is not a fact.

Syllogisms don't require facts:

>> A syllogism is a kind of logical argument that applies deductive reasoning to arrive at a conclusion based on two or more propositions that are asserted or assumed to be true. 

Syllogisms work with assumed *axioms*.

> Scientifically speaking your understanding of theories is wrong. Theories can never be proven regardless of any possible evidence and proofs.

That's funny, because heliocentrism was a theory - and it was proven to be true. Guess, it's not "scientifically speaking" afterall... Also:

> A theory is a contemplative and rational type of abstract or generalizing thinking, or the results of such thinking.

There's nothing indicating that it can't be true. Again, theories don't care about your agreement.

> Theories can only be disproved.

You're making up stuff.

> That means theories can never be a proof.

Yes. And not because theories can't be proven(which is false) but because theories are high-level assertions *which need to be proven first*.

> Facts don't need to be true either. A fact is false if it is disagreed.

You can't be serious... Are you a bot?

First, you tried to make facts strong and clear or "indisputable" and now you're trying to make their definition weaker?

Well, if you only need general agreement and some proof for a fact to be a fact then I guess the "javascript is a poorly designed language" statement is a fact because almost every programmer agrees with it and we also have a lot of evidence to support that fact.

> Disagreeing with a fact does not transform a fact into an opinion.

No, it doesn't. And it doesn't make it false either.

> Facts ~~are~~ *and* opinions are different and non-exchangeable.

FTFY. And yet you're mixing them up with each other without realizing it.

> Facts can be proven true with supporting evidence or false when challenged by evidence.

A "fact" which needs to be proven is not a fact, just an assertion.
Assertions become facts after they get indisputable proofs(which should clearly reflect reality).
But now you're also contradicting one of your previous statements:

>> Facts are simple and primitive.

> Truth is always an opinion

Truth is not an opinion because opinions are inconclusive while the truth is not.
*Disagreement* doesn't change the truth.

> and facts are not opinions.

And yet you say that my fact is an opinion without being able to dispute it.

> An example is a memory.

No, it is not a good example. A memory is just a chunk of data with questionable validity.

> A memory is a thing that exists and that existence is in reality, such that a person really does have a memory.

Opinions also exist in reality - but to be a *fact* it needs to reflect reality.

> A person can document the contents of a memory, but memories are often proven false. The memory does not cease to exist because it is false.

False opinions don't cease to exist either.

> In language people often confuse the agreed state of a thing as a fact

Well, you did confuse them:

>> Facts can be proven true with supporting evidence or false when challenged by evidence.

>> Facts don't need to be true either. A fact is false if it is disagreed.

You're confusing facts with axioms and generally accepted opinions - the main difference is disputability.

> but agreement exceeds factual nature.

They really don't.

> The word fact comes from the Latin equivalent of the English do, facere. The doable nature, possible, of a thing does not equivocate to an agreeable nature, probable.

>> The word "fact" derives from the Latin *factum*, and was first used in English with the same meaning: *a thing done or performed* a meaning now obsolete.

**Comment by prettydiff** [comment]
Truth is a belief, and beliefs are opinions.

> Then I guess "the Earth is spheroidal" statement is not true

Some people will argue it is not.  I recently watched a documentary about people who believe the Earth is flat.  That is their truth.

> but to be a fact it needs to reflect reality.

Facts only need be present in reality, in any tense.  They don't need to reflect or realize anything.

> A memory is just a chunk of data with questionable validity.

All facts have questionable validity.

>Just because you don't agree with something it can still be true.

It could be true to somebody else, but not to you if you don't agree with it.  Truth is a matter of perspective, as agreement dictates, since there is not some universal omnipresent nature of truth.  Some people try to force a universal truth anyways, and that forcing is called ethnocentrism.  And with that I will exit the conversation.

**Comment by ghost** [comment]
> Truth is a belief, and beliefs are opinions.

A belief can be false or unprovable(because of lacking data and tools) just like an opinion but it doesn't work backwards.
If something can be proven then it's no longer a belief.

> Some people will argue it is not.

They can't. They can deny proven things but who cares?

> I recently watched a documentary about people who believe the Earth is flat. That is their truth.

That's not "truth" but delusion. They intentionally deny strong proofs and believe in their own theories. They can't even agree on how the Earth looks like between themselves. There's a theory assuming that they do this because it makes them feel special.

> Facts only need be present in reality, in any tense. They don't need to reflect or realize anything.

Facts need to be present in our abstract human world too. You're thinking about raw unknown data.

> All facts have questionable validity.

They don't, you're thinking about axioms and theories.

> It could be true to somebody else, but not to you if you don't agree with it.

That's an opinion. There's only one property of the "truth": it's true. Your opinion can only be wrong or unprovable.

> Truth is a matter of perspective

Absolutely not, if something is "true" for you and you can't prove it then it can still be a "truth" but it's still just an opinion for now and you're not allowed to classify it as a "truth".

> as agreement dictates

Agreement helps axioms, theories, opinions and beliefs. But agreement can't change the singular state of a truth.

> since there is not some universal omnipresent nature of truth.

No, that's the only nature of truth.

> Some people try to force a universal truth anyways, and that forcing is called ethnocentrism.

No, ethnocentrism is just a way you look at other cultures from the perspective of your own:

>> Ethnocentrism is the act of judging another culture based on preconceptions that are found in the values and standards of one's own culture – especially regarding language, behavior, customs, and religion.

> And with that I will exit the conversation.

@prettydiff I don't understand why did you try to twist the definitions of words so much? I thought that you care about the truth and you wanted to improve this repo and help "delusional" developers...
